### ISSUE TITLE
Standardize on "Prepared for release" final commit

### ISSUE THREAD

**Issue by paulboocock** [snowplow-incubator/engineering-resources#10]
There are currently some ambiguities within https://github.com/snowplow-incubator/engineering-resources/blob/master/release-process.md as to what the final commit should be.

**Prepared for release:**
https://github.com/snowplow-incubator/engineering-resources/blob/95075cfb4f20f24ec6aa2f9b9d2c3741f3179d51/release-process.md#L77

**Prepare to release:**
https://github.com/snowplow-incubator/engineering-resources/blob/95075cfb4f20f24ec6aa2f9b9d2c3741f3179d51/release-process.md#L79
https://github.com/snowplow-incubator/engineering-resources/blob/95075cfb4f20f24ec6aa2f9b9d2c3741f3179d51/release-process.md#L99

**Prepare for release:**
https://github.com/snowplow-incubator/engineering-resources/blob/95075cfb4f20f24ec6aa2f9b9d2c3741f3179d51/release-process.md#L111

I personally prefer `Prepare for release` as this reads easiest to me and feels imperitive like other commit messages. `Prepare to release` doesn't offend me though if that is preferred.

**Comment by dilyand** [comment]
+1 to `Prepare for release` and the imperative mood for commit messages and issue names in general.

**Comment by oguzhanunlu** [comment]
I'm curious if there is any historical reason @chuwy might be aware of.

**Comment by chuwy** [comment]
Not much of historical background, sorry. I think "to" was introduced by me because of my poor English. Happy to stick with "for" if it feels more natural.

No idea where the past tense was introduced though and have no hard feelings for neither option, so let's stick to "Prepare for release" I guess?

**Comment by chuwy** [comment]
Renamed the ticket to reflect our seeming convention.
